name: Build on push
on:
  push:
    paths:
      - "**/*.cs"
      - "*.csproj"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        uses: blankochan/ShrimpleBuilder/build@master
        with:
          configuration: "Debug"
          include_networking_api: true
          download_url: ${{ secrets.REFERENCE_URL }}
